[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink/contracts=lib/chainlink/contracts",
]

[invariant]
runs = 128
depth = 128
fail_on_revert = false # this allows us to run invariant tests, preventing the test to fail if any revert is encountered

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
